name: "Update Virtool Reference"
description: "Updates a Virtool reference repository in-place using the official CLI tool"

inputs:
  
  source-owner:
    description: "Owner of the reference repository to be updated"
    required: true
    default: ${{ github.repository_owner }}
  source-repo:
    description: "'owner/repository_name' of the reference repository to be updated"
    required: true
    default: ${{ github.repository_name }}
  source-ref:
    description: "Branch/Reference to be checked out and updated"
    required: true
    default: 'main'
  source-token:
    description: "Personal access token used to access the repository"
    required: false
    default: ${{ github.token }}

  catalog-repo:
      description: "'owner/repository_name' of the catalog"
      required: true
      default: 'sygao/ref-accession-catalog'
  catalog-token:
      description: "Personal access token used to access the repository"
      required: false
      default: ${{ github.token }}
  
  create-new-branch:
    description: "Create a new branch and commit updates to it"
    required: false
    default: false
  new-branch-name:
    description: "Give a name to a new branch"
    required: false
    default: 'new-accessions'

outputs:
  active-branch: 
    description: "Name of branch committed to"
    value: ${{ steps.branch-name.outputs.active_branch }}

runs:
  using: "composite"

  steps:
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.source.repo }}
        token: ${{ inputs.source.token }}
        ref: ${{ inputs.source.ref }}

    - name: Check out catalog
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.catalog.repo }}
        token: ${{ inputs.catalog.token }}
    
    - name: Get isolates
      run: virtool ref update -src src -cat 

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated virtool-cli isolate retrieval on the database
      if: ${{ inputs.create-new-branch == 'false' }}
    
    - name: Set old branch name
      if: ${{ inputs.create-new-branch == 'false' }}
      run: |
        echo $branch_name
        echo "BRANCH_NAME=$ref" >> ${GITHUB_ENV}
      env:
        ref: ${{ inputs.source.ref }}
      shell: bash
    
    - name: Set branch name
      if: ${{ inputs.create-new-branch == 'true' }}
      run: |
        echo $branch_name
        echo "BRANCH_NAME=$new_name" >> ${GITHUB_ENV}
      env:
        new_name: ${{ inputs.new-branch-name }}
      shell: bash

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: ${{ env.BRANCH_NAME }}
        create_branch: true
        commit_message: Automated virtool-cli isolate retrieval on the database
      if: ${{ inputs.create-new-branch == 'true' }}

    - run: echo "active_branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
      id: branch-name
      shell: bash