name: "Update Virtool Reference"
description: "Updates a reference"
inputs:
  owner:
    description: 'Owner of the reference repository'
    required: true
  repository:
    description: 'Name of the reference repository'
    required: true
  create-branch:
    description: 'Commit updates to a new branch instead of main'
    default: false
  auto-pull:
    description: 'Send a pull request to the official branch automatically'
    default: false
outputs:

runs:
  using: "composite"
  steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Install virtool-cli
      run: |
        git config --global --add safe.directory $PWD
        git status
        pip install virtool-cli
    
    - name: Get isolates
      run: |
        virtool ref taxid -src src
        virtool ref repair -src src
        virtool ref isolate -src src

    - name: Set date for branch naming
      run: |
        branch_date=$(date +"%Y-%m-%d")
        branch_prefix="candidate--"
        branch_name=$branch_prefix$branch_date
        echo $branch_name
        echo "BRANCH_NAME=$branch_name" >> ${GITHUB_ENV}

    # - name: Commit to new branch
    #   uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #     branch: ${{ env.BRANCH_NAME }}
    #     commit_message: Automated virtool-cli isolate retrieval on the database
    #     create_branch: true

    # - name: Make pull request to main branch
    #   uses: actions/github-script@v6
    #   env:
    #     BRANCH_NAME: ${{ env.BRANCH_NAME }}
    #   with:
    #     github-token: ${{ secrets.GH_PAT }}
    #     script: |
    #       const { BRANCH_NAME } = process.env
    #       github.rest.pulls.create({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         head: BRANCH_NAME,
    #         base: "main",
    #         title: BRANCH_NAME
    #       })