name: "Update Virtool Reference"
description: "Updates a Virtool reference repository in-place using the official CLI tool"

inputs:
  
  source-owner:
    description: "Owner of the reference repository to be updated"
    required: true
    default: ${{ github.repository_owner }}
  source-repo:
    description: "'owner/repository_name' of the reference repository to be updated"
    required: true
    default: ${{ github.repository_name }}
  source-ref:
    description: "Branch/Reference to be checked out and updated"
    required: true
    default: 'main'
  source-token:
    description: "Personal access token used to access the repository"
    required: false
    default: ''

  catalog-repo:
    description: "'owner/repository_name' of the catalog"
    required: true
    default: 'sygao/ref-accession-catalog'
  catalog-token:
    description: "Personal access token used to access the repository"
    required: false
    default: ''

  ncbi-email:
    description: "Email to submit to NCBI. Decreases fetch cooldown."
    required: false
    default: ''
  ncbi-api-key:
    description: "NCBI API key. Decreases fetch cooldown."
    required: false
    default: ''
  
  new-branch-name:
    description: "Give a name to a new branch"
    required: false
    default: 'new-accessions'

  debugging:
    description: "Debug flag. Determines verbosity of Virtool logs."
    required: false
    default: false

outputs:
  active-branch: 
    description: "Name of branch committed to"
    value: ${{ steps.branch-name.outputs.active_branch }}

env:
  flags: ''

runs:
  using: "composite"

  steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.source-repo }}
        token: ${{ inputs.source-token }}
        ref: ${{ inputs.source-ref }}

    - name: Check out catalog
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.catalog-repo }}
        token: ${{ inputs.catalog-token }}
        path: .cache

    - name: Double check directory structure
      run: |
        pwd
        ls -la
        ls -la .cache
        ls -la src
      shell: bash

    - run: echo flags='--debug' >> GITHUB_ENV
      if: ${{ inputs.debugging }}
      shell: bash

    - name: Get updated data and update catalog
      run: |
        virtool ref update reference -src src -cat .cache/catalog ${{ env.flags }}
        virtool catalog update -src src -cat catalog ${{ env.flags }}
        rm GITHUB_ENV
      shell: bash
    
    - name: Set branch name
      run: |
        echo $branch_name
        echo "BRANCH_NAME=$new_name" >> ${GITHUB_ENV}
      env:
        new_name: ${{ inputs.new-branch-name }}
      shell: bash

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: ${{ env.BRANCH_NAME }}
        create_branch: true
        commit_message: Automated virtool-cli isolate retrieval on the database

    - run: echo "active_branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
      id: branch-name
      shell: bash