name: "Update Virtool Reference"
description: "Updates a Virtool reference repository in-pace using the official CLI tool"
inputs:
  owner:
    description: 'Owner of the reference repository to be updated'
    required: true
    default: ${{ github.repository_owner }}
  repository:
    description: 'Slug of the reference repository to be updated'
    required: true
    default: ${{ github.repository_name }}
  ref:
    description: 'Branch/Reference to be checked out and updated'
    required: true
    default: 'main'
  token:
    description: Personal access token (PAT) used to run the repository
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}

    - name: Install virtool-cli
      run: |
        git config --global --add safe.directory $PWD
        git status
        pip install virtool-cli
      shell: bash
    
    - name: Get isolates
      run: |
        virtool ref taxid -src src
        virtool ref repair -src src
        virtool ref isolate -src src
      shell: bash

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated virtool-cli isolate retrieval on the database