name: "Update Virtool Reference"
description: "Updates a Virtool reference repository in-place using the official CLI tool"

inputs:
  
  source-owner:
    description: "Owner of the reference repository to be updated"
    required: true
    default: ${{ github.repository_owner }}
  source-repo:
    description: "'owner/repository_name' of the reference repository to be updated"
    required: true
    default: ${{ github.repository_name }}
  source-ref:
    description: "Branch/Reference to be checked out and updated"
    required: true
    default: 'main'
  source-token:
    description: "Personal access token used to access the repository"
    required: false
    default: ''

  catalog-repo:
    description: "'owner/repository_name' of the catalog"
    required: true
    default: 'sygao/ref-accession-catalog'
  catalog-token:
    description: "Personal access token used to access the repository"
    required: false
    default: ''

  ncbi-email:
    description: "Email to submit to NCBI. Decreases fetch cooldown."
    required: false
    default: ''
  ncbi-api-key:
    description: "NCBI API key. Decreases fetch cooldown."
    required: false
    default: ''
  
  new-branch-name:
    description: "The name of the new branch"
    required: false
    default: 'new-accessions'

  debugging:
    description: "Debug flag. Determines verbosity of Virtool logs."
    required: false
    default: false

env:
  FLAGS: ''

runs:
  using: "composite"

  steps:
    - run: echo FLAGS='--debug' >> GITHUB_ENV
        if: ${{ inputs.debugging }}
        shell: bash

    - uses: octokit/request-action@v2.x
        id: get-branch-existence
        continue-on-error: true
        with:
          route: GET /repos/${{ inputs.source-repo }}/branches/${{ inputs.new-branch-name }}
        env:
          GITHUB_TOKEN: ${{ inputs.source-token }}
    
    - name: Abort if branch exists
        if: steps.get-branch-existence.outcome != 'failure'
        run: exit 1
      shell: bash
        
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.source-repo }}
        token: ${{ inputs.source-token }}
        ref: ${{ inputs.source-ref }}

    - name: Check out catalog
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.catalog-repo }}
        token: ${{ inputs.catalog-token }}
        path: .cache

    - name: Get updated data and update catalog
      run: |
        virtool ref update reference -src src -cat .cache/catalog ${{ env.FLAGS }}
        virtool catalog update -src src -cat catalog ${{ env.FLAGS }}
      shell: bash

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: ${{ inputs.new-branch-name }}
        create_branch: true
        file_pattern: '*.json'
        commit_message: Auto-update from NCBI Nucleotide